# Generated by Django 3.0.5 on 2020-04-23 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0003_auto_20200407_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_eaten',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
