# Generated by Django 3.0.5 on 2020-04-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0004_auto_20200423_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
