# Generated by Django 3.0.5 on 2020-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0005_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date_eaten',
            field=models.DateField(auto_now_add=True),
        ),
    ]
