# Generated by Django 3.0.5 on 2020-05-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0006_auto_20200505_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIS',
        ),
    ]
